config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    registrations:  "users/registrations"
  }
  
  devise_scope :user do
    authenticated :user do
      root 'users/users#show', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  namespace :users do
    resources :agencies
    resources :accounts
    resources :transactions do 
      get 'chargeback', on: :member
    end
  end

end

app/models/account.rb
class Account < ApplicationRecord
  
  number_regex = /\A\d+\z/

  validates :number     ,presence: true,
    uniqueness: true, 
    format: { with: number_regex, message: "Apenas números." }
  validates :limit      ,presence: true,
    format: { with: number_regex, message: "Apenas números." }
  validates :user_id    ,presence: true

  belongs_to :user
  belongs_to :agency

  has_many :destination_transactions, class_name: "Transaction", foreign_key: "destination_account_id"
  has_many :origin_transactions,  class_name: "Transaction", foreign_key: "origin_account_id"

  def to_s 
    agency.bank_name + ' - Ag: ' + agency.number + " - Conta: " + number
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name,  presence: true, length:{maximum:15}
  validates :last_name,   presence: true, length:{maximum:25}

  has_many :accounts
  has_many :transactions
  
  def full_name
    "#{first_name} #{last_name}".strip
  end
end

app/controllers/users/accounts_controller.rb
module Users
  class AccountsController < Users::BaseController

    before_action :set_account, except:[:index, :new, :create]
    before_action :authenticate_user!
    respond_to :js, except:[:index, :show, :destroy]
    set_tab :accounts
    
    def index
      @accounts = Account.all
    end

    def new
      @account = Account.new
    end

    def create
      @account = Account.new(account_params.merge(user_id: current_user.id))
      if @account.save
        @accounts = Account.all
        respond_to :js
      else
        respond_to :js
      end
    end

    def show
      @amount = 0
      @account_transactions = Transaction.where(
        origin_account_id: @account.id).or(Transaction.where(
          destination_account_id: @account.id
        )
      )
      @amount = set_amount(@amount, @account_transactions)
    end 

    def edit
    end 

    def update 
      @account.update_attributes(account_params)
    end 

    def destroy
      @account.delete
      redirect_to users_accounts_path(), notice: "Conta deletada com sucesso"
    end

    private
    def set_account
      @account = Account.find(params[:id])
    end

    def account_params
      params.require(:account).permit(
        :number, :limit, :agency_id 
      )
    end

    def set_amount(amount, transactions)
      transactions.each do |transaction|
        if transaction.deposit? || (transaction.transfer? && transaction.destination_account == @account) 
         amount += transaction.amount_in_cents.to_i  
        elsif transaction.withdrawal? || (transaction.transfer? && transaction.origin_account == @account) 
          amount -= transaction.amount_in_cents.to_i  
        end
      end
      return amount
    end
  end
end

app/controllers/users/agencies_controller.rb
module Users
  class AgenciesController < Users::BaseController

    before_action :set_agency, except:[:index, :new, :create]
    before_action :authenticate_user!
    respond_to :js, except:[:index, :show, :destroy]
    set_tab :agencies
    
    def index
      @agencies = Agency.all
    end

    def new
      @agency = Agency.new
    end

    def create
      @agency = Agency.new(agency_params)
      if @agency.save
        @agencies = Agency.all
        respond_to :js
      else
        respond_to :js
      end
    end

    def show
      @accounts = @agency.accounts.where(user_id: current_user)
    end 

    def edit
    end 

    def update 
      @agency.update_attributes(agency_params)
    end 

    def destroy
      @agency.delete
      redirect_to users_agencies_path(), notice: "Conta deletada com sucesso"
    end

    private
    def set_agency
      @agency = Agency.find(params[:id])
    end

    def agency_params
      params.require(:agency).permit(
        :bank_name, :number, :state,       
        :city, :street_name, :building_number
      )
    end
  end
end

app/controllers/users/base_controller.rb
module Users
  class BaseController < ApplicationController
    layout 'user_layout'
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  #def create
  #  super
  #end
  
  # GET /resource/edit
  #def edit
  # super
  #end

  # PUT /resource
  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    resource_updated = update_resource(resource, account_update_params)
    yield resource if block_given?
    if resource_updated
      if is_flashing_format?
        flash_key = update_needs_confirmation?(resource, prev_unconfirmed_email) ?
          :update_needs_confirmation : :updated
        set_flash_message :notice, flash_key
      end
      bypass_sign_in resource, scope: resource_name
      respond_with resource, location: after_update_path_for(resource)
    else
      clean_up_passwords resource
      set_minimum_password_length
      render 'update'
    end
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name,
      :email, :password, :password_confirmation
    ])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name,
    :email, :password, :password_confirmation, :current_password
    ])
  end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/transactions_controller.rb
module Users
  class TransactionsController < Users::BaseController

    before_action :set_transaction, except:[:index, :new, :create]
    before_action :authenticate_user!
    respond_to :js, except:[:index, :show, :destroy]
    set_tab :transactions
    
    def index
      @transactions = Transaction.where(user_id: current_user.id)
    end

    def new
      @transaction = Transaction.new

    end

    def create
      @transaction = Transaction.new(transaction_params.merge(user_id: current_user.id))
      if @transaction.save
        @transactions = Transaction.where(user_id: current_user.id)
        respond_to :js
      else
        respond_to :js
      end
    end

    def show
    end 

    def edit
    end 

    def update 
      @transaction.update_attributes(transaction_params)
    end 

    def chargeback
      @transaction.transaction_type = "chargeback"
      @transaction.save
      flash[:success] = "Transação estornada com sucesso"
    end

    private
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    def transaction_params
      params.require(:transaction).permit(
        :transaction_type, :amount_in_cents, :date,
        :origin_account_id, :destination_account_id
      )
    end
  end
end

app/controllers/users/users_controller.rb
module Users
  class UsersController < Users::BaseController
    before_action :authenticate_user!
    
    def show
      @user = current_user  
    end
  
  end
end

app/views/users/accounts/_edit.html.slim
.modal-content
  h4 Editar Conta
  .divider style="margin-bottom:10px;"
  = render 'form', path: users_account_path(@account), method: :patch

app/views/users/accounts/_form.html.slim
= form_for(@account, url: path, method: method, remote: true) do |f|
  .fields-container
    .field.field-item
      = form_group_for f, :number, label: false  do
        = f.label :number, class:"form-label"
        = f.text_field :number, autofocus: true, class:"form-field"  
    .field.field-item
      = form_group_for f, :limit, label: false  do
        = f.label :limit, class:"form-label"
        = f.text_field :limit, class:"form-field"
  h5 style="margin-top:0px;" Agência 
  .divider style="margin-bottom:10px;"" 
  .field.field-item
    = form_group_for f, :agency_id, label: false  do
      = f.label :agency_id, class:"form-label"
      = f.select :agency_id, options_from_collection_for_select(Agency.all, "id", "to_s", selected: @account.agency_id), include_blank: true, class:"form-field"
  .actions
    = f.submit "SALVAR",class:"btn green-btn green-btn-center btn-full-width", id:"submit-button"

app/views/users/accounts/_index.html.slim
- @accounts.each do |account|
  .card-container-item
    = link_to users_account_path(account) do
      .card.content-card
        .center
          = account.agency.bank_name
        .divider
        p Agência: #{account.agency.number}
        p Conta: #{account.number}
  

app/views/users/accounts/_index_validations.html.slim
- if agencies?
  = link_to "Criar Conta", new_users_account_path(), class:"btn blue-btn", remote: true
  .card-container 
    - if accounts?
      = render 'index', accounts: @accounts
    - else 
      h5.center Não há contas cadastradas
- else
  h5.center Crie uma agência para poder realizar movimentações

app/views/users/accounts/_new.html.slim
.modal-content
  h4 Criar Conta
  .divider style="margin-bottom:10px;"
  = render 'form', path: users_accounts_path(), method: :post

app/views/users/accounts/_save.js.erb
<% if @account.errors.any? %>
  toastr.error("Erro");
  $("<%=id%>").html("<%= escape_javascript(render action) %>")
  $('select').material_select();  
<% else %>
  toastr.success("Sucesso");
  $("<%=partial_id%>").html("<%= escape_javascript(render partial) %>")
  $("<%=id%>").modal("close")
<% end %>

app/views/users/accounts/_show.html.slim
.row
  .col.s12.m6
    h5 Banco:    #{@account.agency.bank_name}
  .col.s12.m6
    h5 Agência:  #{@account.agency.number}
  .col.s12.m6
    h5 Conta:  #{@account.number}
  .col.s12.m6
    h5 Limite:  #{number_to_currency((@account.limit.to_f/10), unit: "R$")}
.row
  .col.s12.m6.btn-container
    = link_to "Editar", edit_users_account_path(@account), class:"btn blue-btn", remote: true
    - unless @account.origin_transactions.any? || @account.destination_transactions.any?
      = link_to "Excluir", users_account_path(@account), method: :delete, data:{confirm: "Confirma a exclusão da conta?"}, remote: true ,class:"btn orange-btn"
p.center Só será possível excuir uma conta se não houver transações vinculadas a ela

app/views/users/accounts/_transactions_resume.html.slim
table
  thead
    tr
      th Tipo
      th Data
      th Valor
  tbody
    - @account_transactions.each do |transaction|
      tr 
        td #{ transaction.chargeback? ?  chargeback_type(transaction) : transaction.t_enum("transaction_type")}
        td #{transaction.date}
        td #{transaction_amount(transaction, @account)}
  

app/views/users/accounts/create.js.erb
<%= render 'save', id: "#account-form-modal",action: "new",  partial: "index_validations", partial_id:"#accounts"%>

app/views/users/accounts/edit.js.erb
$("#account-form-modal").html("<%= escape_javascript(render 'edit') %>")
$("#account-form-modal").modal("open")
$('select').material_select();  
$('#account_limit').priceFormat({
  prefix: 'R$ ',
  centsSeparator: ',',
  thousandsSeparator: '.'
});

app/views/users/accounts/index.html.slim
h4.title Contas
.card.user-card
  h5.card-title Dados
  .divider
  .card-data id="accounts"
    = render "index_validations"
      
.modal id="account-form-modal"

app/views/users/accounts/new.js.erb
$("#account-form-modal").modal({
  ready: function(modal, trigger) {
    $("#submit-button").on('click', function(e){
      dataAdjustment("#account_limit");
      $("#submit-button").submit();
    });
  }
});

$("#account-form-modal").html("<%= escape_javascript(render 'new') %>")
$('select').material_select();
$("#account-form-modal").modal("open")
$('#account_limit').priceFormat({
  prefix: 'R$ ',
  centsSeparator: ',',
  thousandsSeparator: '.'
});

app/views/users/accounts/show.html.slim
h4.title Contas
.card.user-card
  .tab-style
    ul.tabs
      li.tab
        a.selected id="first-tab" href="#account-data" Dados
      li.tab
        a id="second-tab" href="#account-transactions" Movimentações
      .divider.tab-divider
  . id="account-data"
    .card-data id="account-show"
      .row
        .col.s12
          - if @amount > 0  
            h5.amount-green Saldo #{number_to_currency((@amount.to_f/100), unit: "R$") }   
          - else
            h5.amount-orange Saldo #{number_to_currency((@amount.to_f/100), unit: "R$") }   
      = render "show"
  . id="account-transactions"
    h5 Extrato
    - if @amount > 0  
      h5.amount-green Saldo #{number_to_currency((@amount.to_f/100), unit: "R$") }   
    - else
      h5.amount-orange Saldo #{number_to_currency((@amount.to_f/100), unit: "R$") }   
    .divider
    = render "transactions_resume"
      

.modal id="account-form-modal"

app/views/users/accounts/update.js.erb
<%= render 'save', id: "#account-form-modal", action: "edit", partial: "show", partial_id:"#account-show"%>