config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    registrations:  "users/registrations"
  }
  
  devise_scope :user do
    authenticated :user do
      root 'users/users#show', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  namespace :users do
    resources :agencies
    resources :accounts
    resources :transactions do 
      get 'chargeback', on: :member
    end
  end

end

app/models/agency.rb
class Agency < ApplicationRecord
  
  char_regex = /(^[a-z ]+$)/i
  number_regex = /\A\d+\z/

  validates :bank_name      ,
   presence: true,
   format: { with: char_regex, message: "Apenas caractéres." }
  validates :number         , presence: true, 
    uniqueness: true, 
    format: { with: number_regex, message: "Apenas números." }
  validates :state          , presence: true
  validates :city           , presence: true
  validates :street_name    , presence: true
  validates :building_number, presence: true
  
  has_many :accounts

  def to_s
    bank_name + " - Ag: " + number
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name,  presence: true, length:{maximum:15}
  validates :last_name,   presence: true, length:{maximum:25}

  has_many :accounts
  has_many :transactions
  
  def full_name
    "#{first_name} #{last_name}".strip
  end
end

app/controllers/users/accounts_controller.rb
module Users
  class AccountsController < Users::BaseController

    before_action :set_account, except:[:index, :new, :create]
    before_action :authenticate_user!
    respond_to :js, except:[:index, :show, :destroy]
    set_tab :accounts
    
    def index
      @accounts = Account.all
    end

    def new
      @account = Account.new
    end

    def create
      @account = Account.new(account_params.merge(user_id: current_user.id))
      if @account.save
        @accounts = Account.all
        respond_to :js
      else
        respond_to :js
      end
    end

    def show
      @amount = 0
      @account_transactions = Transaction.where(
        origin_account_id: @account.id).or(Transaction.where(
          destination_account_id: @account.id
        )
      )
      @amount = set_amount(@amount, @account_transactions)
    end 

    def edit
    end 

    def update 
      @account.update_attributes(account_params)
    end 

    def destroy
      @account.delete
      redirect_to users_accounts_path(), notice: "Conta deletada com sucesso"
    end

    private
    def set_account
      @account = Account.find(params[:id])
    end

    def account_params
      params.require(:account).permit(
        :number, :limit, :agency_id 
      )
    end

    def set_amount(amount, transactions)
      transactions.each do |transaction|
        if transaction.deposit? || (transaction.transfer? && transaction.destination_account == @account) 
         amount += transaction.amount_in_cents.to_i  
        elsif transaction.withdrawal? || (transaction.transfer? && transaction.origin_account == @account) 
          amount -= transaction.amount_in_cents.to_i  
        end
      end
      return amount
    end
  end
end

app/controllers/users/agencies_controller.rb
module Users
  class AgenciesController < Users::BaseController

    before_action :set_agency, except:[:index, :new, :create]
    before_action :authenticate_user!
    respond_to :js, except:[:index, :show, :destroy]
    set_tab :agencies
    
    def index
      @agencies = Agency.all
    end

    def new
      @agency = Agency.new
    end

    def create
      @agency = Agency.new(agency_params)
      if @agency.save
        @agencies = Agency.all
        respond_to :js
      else
        respond_to :js
      end
    end

    def show
      @accounts = @agency.accounts.where(user_id: current_user)
    end 

    def edit
    end 

    def update 
      @agency.update_attributes(agency_params)
    end 

    def destroy
      @agency.delete
      redirect_to users_agencies_path(), notice: "Conta deletada com sucesso"
    end

    private
    def set_agency
      @agency = Agency.find(params[:id])
    end

    def agency_params
      params.require(:agency).permit(
        :bank_name, :number, :state,       
        :city, :street_name, :building_number
      )
    end
  end
end

app/controllers/users/base_controller.rb
module Users
  class BaseController < ApplicationController
    layout 'user_layout'
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  #def create
  #  super
  #end
  
  # GET /resource/edit
  #def edit
  # super
  #end

  # PUT /resource
  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    resource_updated = update_resource(resource, account_update_params)
    yield resource if block_given?
    if resource_updated
      if is_flashing_format?
        flash_key = update_needs_confirmation?(resource, prev_unconfirmed_email) ?
          :update_needs_confirmation : :updated
        set_flash_message :notice, flash_key
      end
      bypass_sign_in resource, scope: resource_name
      respond_with resource, location: after_update_path_for(resource)
    else
      clean_up_passwords resource
      set_minimum_password_length
      render 'update'
    end
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name,
      :email, :password, :password_confirmation
    ])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name,
    :email, :password, :password_confirmation, :current_password
    ])
  end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/transactions_controller.rb
module Users
  class TransactionsController < Users::BaseController

    before_action :set_transaction, except:[:index, :new, :create]
    before_action :authenticate_user!
    respond_to :js, except:[:index, :show, :destroy]
    set_tab :transactions
    
    def index
      @transactions = Transaction.where(user_id: current_user.id)
    end

    def new
      @transaction = Transaction.new

    end

    def create
      @transaction = Transaction.new(transaction_params.merge(user_id: current_user.id))
      if @transaction.save
        @transactions = Transaction.where(user_id: current_user.id)
        respond_to :js
      else
        respond_to :js
      end
    end

    def show
    end 

    def edit
    end 

    def update 
      @transaction.update_attributes(transaction_params)
    end 

    def chargeback
      @transaction.transaction_type = "chargeback"
      @transaction.save
      flash[:success] = "Transação estornada com sucesso"
    end

    private
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    def transaction_params
      params.require(:transaction).permit(
        :transaction_type, :amount_in_cents, :date,
        :origin_account_id, :destination_account_id
      )
    end
  end
end

app/controllers/users/users_controller.rb
module Users
  class UsersController < Users::BaseController
    before_action :authenticate_user!
    
    def show
      @user = current_user  
    end
  
  end
end

app/views/users/agencies/_accounts.html.slim
- @accounts.each do |account|
  .card-container-item
    = link_to users_account_path(account) do
      .card.content-card style="width:auto;"
        .center
          = account.agency.bank_name +  " - " +account.agency.number
        .divider
        p Conta: #{account.number}
        p Limite:  #{number_to_currency((account.limit.to_f/10), unit: "R$")}

app/views/users/agencies/_edit.html.slim
.modal-content
  h4 Editar Agência
  .divider style="margin-bottom:10px;"
  = render 'form', path: users_agency_path(@agency), method: :patch

app/views/users/agencies/_form.html.slim
= form_for(@agency, url: path, method: method, remote: true) do |f|
  .fields-container
    .field.field-item
      = form_group_for f, :bank_name, label: false  do
        = f.label :bank_name, class:"form-label"
        = f.text_field :bank_name, autofocus: true, class:"form-field"
    .field.field-item
      = form_group_for f, :number, label: false  do
        = f.label :number, class:"form-label"
        = f.text_field :number, class:"form-field"
  h5 style="margin-top:0px;" Endereço 
  .divider style="margin-bottom:10px;"" 
  .fields-container
    .field.field-item
      = form_group_for f, :state, label: false  do
        = f.label :state, class:"form-label"
        = f.text_field :state,class:"form-field"
    .field.field-item
      = form_group_for f, :city, label: false  do
        = f.label :city, class:"form-label"
        = f.text_field :city, autocomplete: "off", class:"form-field"
  .fields-container
    .field.field-item
      = form_group_for f, :street_name, label: false  do
        = f.label :street_name, class:"form-label"
        = f.text_field :street_name, autocomplete: "off", class:"form-field"
    .field.field-item
      = form_group_for f, :building_number, label: false  do
        = f.label :building_number, class:"form-label"
        = f.text_field :building_number, autocomplete: "off", class:"form-field"        
  .actions
    = f.submit "SALVAR",class:"btn green-btn green-btn-center btn-full-width", id:"agency-submit-button"

app/views/users/agencies/_index.html.slim
- @agencies.each do |agency|
  .card-container-item
    = link_to users_agency_path(agency) do
      .card.content-card style="width:auto;"
        .center
          = agency.bank_name
        .divider
        p Agência: #{agency.number}
        p Endereço: #{agency.street_name}, #{agency.building_number}
  

app/views/users/agencies/_index_validations.html.slim
= link_to "Criar Agência", new_users_agency_path(), class:"btn blue-btn", remote: true
- if agencies?
  .card-container
      = render 'index', agencies: @agencies
- else 
 h5.center Não há agências cadastradas

app/views/users/agencies/_new.html.slim
.modal-content
  h4 Criar Agência
  .divider style="margin-bottom:10px;"
  = render 'form', path: users_agencies_path(), method: :post

app/views/users/agencies/_save.js.erb
<% if @agency.errors.any? %>
  toastr.error("Erro");
  $("<%=id%>").html("<%= escape_javascript(render action) %>")
<% else %>
  toastr.success("Sucesso");
  $("<%=partial_id%>").html("<%= escape_javascript(render partial) %>")
  $("<%=id%>").modal("close")
<% end %>

app/views/users/agencies/_show.html.slim
.row
  .col.s12.m6
    h5 Banco:    #{@agency.bank_name}
  .col.s12.m6
    h5 Agência:  #{@agency.number}
.row  
  .col.s12
    h5 Endereço
    .divider
  .col.s12.m6
    p Estado:   #{@agency.state}
    p Cidade:   #{@agency.city}
  .col.s12.m6
    p Rua:      #{@agency.street_name}
    p Número:   #{@agency.building_number}
.row
  .col.s12.m6.btn-container
    = link_to "Editar", edit_users_agency_path(@agency), class:"btn blue-btn", remote: true
    - unless @agency.accounts.any?
      = link_to "Excluir", users_agency_path(@agency), method: :delete, data:{confirm: "Confirma o cancelamento da agência?"}, remote: true ,class:"btn orange-btn"
p.center Só será possível excuir uma agência se não houver contas vinculadas a ela

app/views/users/agencies/create.js.erb
<%= render 'save', id: "#new-agency-modal",action: "new",  partial: "index_validations", partial_id:"#agencies"%>

app/views/users/agencies/edit.js.erb
$("#edit-agency-modal").html("<%= escape_javascript(render 'edit') %>")
$("#edit-agency-modal").modal("open")

app/views/users/agencies/index.html.slim
h4.title Agências
.card.user-card
  h5.card-title Dados
  .divider
  .card-data id="agencies"
    = render "index_validations"
.modal id="new-agency-modal"
.modal id="edit_agency_modal"

app/views/users/agencies/new.js.erb
$("#new-agency-modal").html("<%= escape_javascript(render 'new') %>")
$("#new-agency-modal").modal("open")

app/views/users/agencies/show.html.slim
h4.title Agências
.card.user-card
  .tab-style
    ul.tabs
      li.tab
        a.selected id="first-tab" href="#agency-data" Dados
      li.tab
        a id="second-tab" href="#agency-accounts" Contas
      .divider.tab-divider
  . id="agency-data"
    .card-data id="agency-show"
      = render "show"
  . id="agency-accounts"
    .card-data
      = render "accounts"      

.modal id="edit-agency-modal"

app/views/users/agencies/update.js.erb
<%= render 'save', id: "#edit-agency-modal", action: "edit", partial: "show", partial_id:"#agency-show"%>