config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    registrations:  "users/registrations"
  }
  
  devise_scope :user do
    authenticated :user do
      root 'users/users#show', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  namespace :users do
    resources :agencies
    resources :accounts
    resources :transactions do 
      get 'chargeback', on: :member
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name,  presence: true, length:{maximum:15}
  validates :last_name,   presence: true, length:{maximum:25}

  has_many :accounts
  has_many :transactions
  
  def full_name
    "#{first_name} #{last_name}".strip
  end
end

app/controllers/users/accounts_controller.rb
module Users
  class AccountsController < Users::BaseController

    before_action :set_account, except:[:index, :new, :create]
    before_action :authenticate_user!
    respond_to :js, except:[:index, :show, :destroy]
    set_tab :accounts
    
    def index
      @accounts = Account.all
    end

    def new
      @account = Account.new
    end

    def create
      @account = Account.new(account_params.merge(user_id: current_user.id))
      if @account.save
        @accounts = Account.all
        respond_to :js
      else
        respond_to :js
      end
    end

    def show
      @amount = 0
      @account_transactions = Transaction.where(
        origin_account_id: @account.id).or(Transaction.where(
          destination_account_id: @account.id
        )
      )
      @amount = set_amount(@amount, @account_transactions)
    end 

    def edit
    end 

    def update 
      @account.update_attributes(account_params)
    end 

    def destroy
      @account.delete
      redirect_to users_accounts_path(), notice: "Conta deletada com sucesso"
    end

    private
    def set_account
      @account = Account.find(params[:id])
    end

    def account_params
      params.require(:account).permit(
        :number, :limit, :agency_id 
      )
    end

    def set_amount(amount, transactions)
      transactions.each do |transaction|
        if transaction.deposit? || (transaction.transfer? && transaction.destination_account == @account) 
         amount += transaction.amount_in_cents.to_i  
        elsif transaction.withdrawal? || (transaction.transfer? && transaction.origin_account == @account) 
          amount -= transaction.amount_in_cents.to_i  
        end
      end
      return amount
    end
  end
end

app/controllers/users/agencies_controller.rb
module Users
  class AgenciesController < Users::BaseController

    before_action :set_agency, except:[:index, :new, :create]
    before_action :authenticate_user!
    respond_to :js, except:[:index, :show, :destroy]
    set_tab :agencies
    
    def index
      @agencies = Agency.all
    end

    def new
      @agency = Agency.new
    end

    def create
      @agency = Agency.new(agency_params)
      if @agency.save
        @agencies = Agency.all
        respond_to :js
      else
        respond_to :js
      end
    end

    def show
      @accounts = @agency.accounts.where(user_id: current_user)
    end 

    def edit
    end 

    def update 
      @agency.update_attributes(agency_params)
    end 

    def destroy
      @agency.delete
      redirect_to users_agencies_path(), notice: "Conta deletada com sucesso"
    end

    private
    def set_agency
      @agency = Agency.find(params[:id])
    end

    def agency_params
      params.require(:agency).permit(
        :bank_name, :number, :state,       
        :city, :street_name, :building_number
      )
    end
  end
end

app/controllers/users/base_controller.rb
module Users
  class BaseController < ApplicationController
    layout 'user_layout'
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  #def create
  #  super
  #end
  
  # GET /resource/edit
  #def edit
  # super
  #end

  # PUT /resource
  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    resource_updated = update_resource(resource, account_update_params)
    yield resource if block_given?
    if resource_updated
      if is_flashing_format?
        flash_key = update_needs_confirmation?(resource, prev_unconfirmed_email) ?
          :update_needs_confirmation : :updated
        set_flash_message :notice, flash_key
      end
      bypass_sign_in resource, scope: resource_name
      respond_with resource, location: after_update_path_for(resource)
    else
      clean_up_passwords resource
      set_minimum_password_length
      render 'update'
    end
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name,
      :email, :password, :password_confirmation
    ])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name,
    :email, :password, :password_confirmation, :current_password
    ])
  end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/transactions_controller.rb
module Users
  class TransactionsController < Users::BaseController

    before_action :set_transaction, except:[:index, :new, :create]
    before_action :authenticate_user!
    respond_to :js, except:[:index, :show, :destroy]
    set_tab :transactions
    
    def index
      @transactions = Transaction.where(user_id: current_user.id)
    end

    def new
      @transaction = Transaction.new

    end

    def create
      @transaction = Transaction.new(transaction_params.merge(user_id: current_user.id))
      if @transaction.save
        @transactions = Transaction.where(user_id: current_user.id)
        respond_to :js
      else
        respond_to :js
      end
    end

    def show
    end 

    def edit
    end 

    def update 
      @transaction.update_attributes(transaction_params)
    end 

    def chargeback
      @transaction.transaction_type = "chargeback"
      @transaction.save
      flash[:success] = "Transação estornada com sucesso"
    end

    private
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    def transaction_params
      params.require(:transaction).permit(
        :transaction_type, :amount_in_cents, :date,
        :origin_account_id, :destination_account_id
      )
    end
  end
end

app/controllers/users/users_controller.rb
module Users
  class UsersController < Users::BaseController
    before_action :authenticate_user!
    
    def show
      @user = current_user  
    end
  
  end
end

app/views/users/transactions/_edit.html.slim
.modal-content
  h4 Editar Movimentação
  .divider style="margin-bottom:10px;"
  = render 'form', path: users_transaction_path(@transaction), method: :patch

app/views/users/transactions/_form.html.slim
= form_for(@transaction, url: path, method: method, remote: true) do |f|
  .field.field-select id="transaction-type-field"
    = form_group_for f, :transaction_type, label: false  do
      = f.label :transaction_type, class:"form-label"
      = f.select :transaction_type, options_for_transaction_type(), include_blank: true, class:"form-field", id:"origin_type"
  .field.field-select id="origin-account-field"
    = form_group_for f, :origin_account_id, label: false  do
      = f.label :origin_account_id, class:"form-label"
      = f.select :origin_account_id, 
          options_from_collection_for_select(my_accounts, "id", "to_s", selected: @transaction.origin_account_id), 
          include_blank: true, class:"form-field", id:"origin_account_id"
  .field.field-select id="destination-account-field"
    = form_group_for f, :destination_account_id, label: false  do
      = f.label :destination_account_id, class:"form-label"
      = f.select :destination_account_id, 
          options_from_collection_for_select(accounts, "id", "to_s", selected: @transaction.destination_account_id, id:"destination_account_select"),
          include_blank: true, class:"form-field"
  .fields-container
    .field.field-item
      = form_group_for f, :amount_in_cents, label: false  do
        = f.label :amount_in_cents, class:"form-label"
        = f.text_field :amount_in_cents, class:"form-field"  
    .field.field-item
      = form_group_for f, :date, label: false  do
        = f.label :date, class:"form-label"
        = f.text_field :date, class:"form-field"
  .actions
    = f.submit "SALVAR",class:"btn green-btn green-btn-center btn-full-width", id:"submit-button"

app/views/users/transactions/_index.html.slim
- @transactions.each do |transaction|
  .card-container-item
    = link_to users_transaction_path(transaction) do
      .card.content-card
        .center
          - if transaction.chargeback?
            = chargeback_type(transaction)
          - else
            = transaction.t_enum("transaction_type")
        .divider
        p Valor: #{number_to_currency((transaction.amount_in_cents.to_f/100), unit: "R$") }
        - if transaction.deposit?
          =  "Para -> ag: " + transaction.destination_account.agency.number + " -  conta: " + transaction.destination_account.number
        - if transaction.withdrawal?
          =  "De -> ag: " + transaction.origin_account.agency.number + " -  conta: " + transaction.origin_account.number
        - if transaction.transfer?        
          =  "De -> ag: " + transaction.origin_account.agency.number + " -  conta: " + transaction.origin_account.number
          =  "Para -> ag: " + transaction.destination_account.agency.number + " -  conta: " + transaction.destination_account.number
        - if transaction.chargeback?
          - if transaction.origin_account        
            =  "De -> ag: " + transaction.origin_account.agency.number + " -  conta: " + transaction.origin_account.number
          - if transaction.destination_account
            =  "Para -> ag: " + transaction.destination_account.agency.number + " -  conta: " + transaction.destination_account.number

app/views/users/transactions/_index_validations.html.slim
- if accounts?
  = link_to "Criar Movimentação", new_users_transaction_path(), class:"btn blue-btn", remote: true
  .card-container 
    - if transactions?
      = render 'index', transactions: @transactions
    - else 
      h5.center Não há movimentações cadastradas
- else
  h5.center Crie uma conta para poder realizar movimentações

app/views/users/transactions/_new.html.slim
.modal-content
  h4 Criar Movimentação
  .divider style="margin-bottom:10px;"
  = render 'form', path: users_transactions_path(), method: :post

app/views/users/transactions/_save.js.erb
<% if @transaction.errors.any? %>
  <%byebug%>
  toastr.error("<%=@transaction.errors.first[1]%>");
  $("<%=id%>").html("<%= escape_javascript(render action) %>")
  $('select').material_select();  
<% else %>
  toastr.success("Sucesso");
  $("<%=partial_id%>").html("<%= escape_javascript(render partial) %>")
  $("<%=id%>").modal("close")
<% end %>

app/views/users/transactions/_show.html.slim
.row
  .col.s12
    - if @transaction.chargeback?
      h5 #{chargeback_type(@transaction)}
    - else
      h5 = @transaction.t_enum("transaction_type")
.divider
.row
  .col.s12
    - if @transaction.deposit?
      =  "Para -> ag: " + @transaction.try(:destination_account).agency.number + " -  conta: " + @transaction.destination_account.number
    - if @transaction.withdrawal?
      =  "De -> ag: " + @transaction.try(:origin_account).agency.number + " -  conta: " + @transaction.origin_account.number
    - if @transaction.transfer?        
      =  "De -> ag: " + @transaction.try(:origin_account).agency.number + " -  conta: " + @transaction.origin_account.number
      =  "Para -> ag: " + @transaction.try(:destination_account).agency.number + " -  conta: " + @transaction.destination_account.number
    - if @transaction.chargeback?
      - if @transaction.origin_account        
        =  "De -> ag: " + @transaction.origin_account.agency.number + " -  conta: " + @transaction.origin_account.number
      - if @transaction.destination_account
        =  "Para -> ag: " + @transaction.destination_account.agency.number + " -  conta: " + @transaction.destination_account.number
    p Valor: #{number_to_currency((@transaction.amount_in_cents.to_f/100), unit: "R$") }  
  

app/views/users/transactions/chargeback.js.erb
  toastr.success("Transação estornada com sucesso");
  $("#transaction-show").html("<%= escape_javascript(render "show") %>")

app/views/users/transactions/create.js.erb
<%= render 'save', id: "#transaction-form-modal",
    action: "new",  partial: "index_validations", partial_id:"#transactions"
%>

app/views/users/transactions/edit.js.erb
$("#transaction-form-modal").html("<%= escape_javascript(render 'edit') %>")
$("#transaction-form-modal").modal("open")
$('select').material_select();  

app/views/users/transactions/index.html.slim
h4.title Movimentações
.card.user-card
  h5.card-title Dados
  .divider
  .card-data id="transactions"
    = render "index_validations"

.modal id="transaction-form-modal"

app/views/users/transactions/new.js.erb
$("#transaction-form-modal").html("<%= escape_javascript(render 'new') %>")
$('select').material_select();
$("#transaction-form-modal").modal("open")
$('#transaction_amount_in_cents').priceFormat({
  prefix: 'R$ ',
  centsSeparator: ',',
  thousandsSeparator: '.'
});



$('#transaction_date').pickadate({
  selectMonths: true,
  selectYears: 15,
  // Título dos botões de navegação
  labelMonthNext: 'Próximo Mês',
  labelMonthPrev: 'Mês Anterior',
  // Título dos seletores de mês e ano
  labelMonthSelect: 'Selecione o Mês',
  labelYearSelect: 'Selecione o Ano',
  // Meses e dias da semana
  monthsFull: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
  monthsShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
  weekdaysFull: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
  weekdaysShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab'],
  // Letras da semana
  weekdaysLetter: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],
  //Botões
  today: 'Hoje',
  clear: 'Limpar',
  close: 'Fechar',
  // Formato da data que aparece no input
  format: 'dd/mm/yyyy',
  onClose: function() {
    $(document.activeElement).blur()
  }
});

app/views/users/transactions/show.html.slim
h4.title Movimentações
.card.user-card
  .tab-style
    ul.tabs
      li.tab
        a.selected id="first-tab" href="#transaction-data" Dados
      .divider.tab-divider
  . id="transaction-data"
    .card-data id="transaction-show"
      = render "show"
  
  .col.s12.m6.offset-m3.btn-container
    = link_to "Editar", edit_users_transaction_path(@transaction), class:"btn blue-btn", remote: true
    = link_to "Estornar", chargeback_users_transaction_path(@transaction), class:"btn orange-btn", remote: true
.modal id="transaction-form-modal"

app/views/users/transactions/update.js.erb
<%= render 'save', id: "#transaction-form-modal", action: "edit", partial: "show", partial_id:"#transaction-show"%>